version: "2"

services:
  pptp-server:
    build: .
    image: scue/pptp-server:0.1.0
    environment:
      - USERNAME=scue
      - PASSWORD=awesome
    privileged: yes
    ports:
      - "1723:1723"
    network_mode: "bridge"
